### PR TITLE
Php7-3

### PR DESCRIPTION
**Pull request by marklchaves**
**PHP 7.3**

Replaced one call to deprecated `create_function`. Deprecated in 7.2.

**jscolor**

Installed latest jscolor (version 2.0.5). http://jscolor.com/release/latest.zip

**Typos**

- Removed extra "w" in plugin description. Used to be wwww.ko-fi.com.
- Made Ko-fi init cap throughout as per website. E.g. not ko-fi or Ko-Fi.

**Testing**

PHP 7.3.2 and WordPress 5.3. Safari 13.0.4, Firefox 71, and Chrome 78 on MacOS.

1. Tested plugin with `wp_debug` on. Observed deprecated warning. No other warnings.
2. Ran PHP Compatibility (WP Engine) scan. Observed deprecated warning. No other warnings.
3. Converted create_function call to anonymous function (PHP closure). 
4. Tested plugin settings and widget. No warnings logged. All functions worked (see questions below).
5. Ran PHP Compatibility scan. No warnings logged.

**Notes**

Only question was if unchecking the **Hyperlink** setting is supposed to _disable_ linking for the widget? Oh, it looks like there's support for a custom _shortcode_? Any documentation on that? I can test that too.

**Attached** before/after logs.

ko-fi-button-debug-log-deprecated-12dec2019

ko-fi-button-php-compatibility-checker-deprecated-11dec2019
ko-fi-button-php-compatibility-checker-12dec2019

[ko-fi-button-php-compatibility-report-11dec2019.txt](https://github.com/Ko-fi/kofi-wordpress-button/files/3954822/ko-fi-button-php-compatibility-report-11dec2019.txt)
[ko-fi-button-php-compatibility-report-12dec2019.txt](https://github.com/Ko-fi/kofi-wordpress-button/files/3954823/ko-fi-button-php-compatibility-report-12dec2019.txt)

Note: Sorry about the FUNDING.yml update. Didn't realised this file would be included 😬 Feel free to delete?

### CODE REVIEW

**Comment by max23468** [comment]
Any news about this fix?

**Comment by marklchaves** [comment]
Hi @max23468,

Still waiting for a review. I hope we'll get one soon!

Thanks for asking.

**Comment by Jarrich** [comment]
Sorry for the silence. You can expect some movement on this soon 👍

**Comment by max23468** [comment]
Hope to see some updated to the plugin soon!
It needs a bit of improvement because it's risks to become obsolete as WP gets support for newer PHP versions

**Comment by Jarrich** [comment]
Thank you for the contribution @marklchaves

**Pull request merged**
